/* User-visible texts, in Italian. The code reads them as T.<key>; keys are
   named after the function that shows them. Functions take the values to
   insert (amounts, names) in the order they appear in the sentence. */
export const T = {
  contributionItems: {
    ivs: 'IVS (FPLD)', naspi: 'NASpI e formazione', cuaf: 'CUAF (assegni familiari)', cigo: 'CIG ordinaria',
    cigs: 'CIG straordinaria', tfr: 'Fondo di garanzia TFR', sickness: 'Indennità di malattia',
    maternity: 'Indennità di maternità'
  },
  badgeExpired: 'scaduto',
  deductionAnnualBand: 'Quota a scaglioni annua',
  deductionBandCorrection: '+ correttivo di fascia, intero',
  deductionFloorApplied: 'Pavimento di legge applicato',
  expiredMeasures: (count) => `${count} misur${count === 1 ? 'a scaduta' : 'e scadute'}`,
  welfareSummaryNone: 'Nessuna voce inserita: fringe benefit, buoni pasto, premi, fondo pensione, trattenute',
  welfareSummary: (count) => `${count} voc${count === 1 ? 'e inserita' : 'i inserite'}`,
  exemptionsSummaryNone: 'Nessun esonero selezionato',
  exemptionsSummary: (count) => `${count} esoner${count === 1 ? 'o selezionato' : 'i selezionati'}`,
  testsPassed: (passed, total) => `${passed}/${total} test superati`,
  badgeRecommended: 'costo minore',
  badgeSelected: 'selezionato',
  card_1: 'della lavoratrice',
  card_2: 'del datore',
  card_3: (a1, a2) => `${a1} &middot; incide sui contributi ${a2}`,
  card_4: (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) => `
      <label class="flex items-start gap-3 rounded-xl border p-3 transition ${a1}">
        <input type="checkbox" class="exemption-check mt-0.5 h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500"
               data-hiring-exemption="${a2}" ${a3} ${a4} />
        <span class="text-sm min-w-0">
          <span class="font-semibold text-slate-700">${a5}</span>
          ${a6}
          ${a7}
          <span class="block text-xs text-slate-600 mt-0.5">
            ${a8}
          </span>
          <span class="block text-[11px] text-slate-600 mt-1">${a9} &middot; verificato il ${a10}</span>
        </span>
      </label>`,
  chooseView_1: 'A parità di tutti gli altri parametri',
  chooseView_2: 'Tutto ciò che passa dalla busta, e dove va a finire',
  chooseView_3: 'Curva netto / RAL',
  chooseView_4: 'Come si divide il lordo',
  CONTRACT_TYPES_name_1: 'Collaborazione coordinata e continuativa',
  CONTRACT_TYPES_note_1: `L’indennità non è reddito di lavoro dipendente ma assimilato (art. 50, comma 1, lett. c TUIR): nessun contributo previdenziale, nessun TFR, nessuna mensilità aggiuntiva.`,
  CONTRACT_TYPES_note_2: `Gestione separata INPS: 35,03% complessivo, un terzo al collaboratore e due terzi al committente, entro il massimale di 122.295 €. Il compenso e’ reddito assimilato a quello di lavoro dipendente (art. 50, comma 1, lett. c-bis TUIR): spettano le detrazioni da lavoro dipendente e il trattamento integrativo, non il taglio del cuneo, riservato ai redditi dell’art. 49. Nessun TFR, nessuna mensilita’ aggiuntiva.`,
  CONTRACT_TYPES_note_3: 'Aliquota agevolata per legge, indipendente dal settore: 5,84% a carico dell’apprendista.',
  CONTRACT_TYPES_note_4: `Contributo addizionale NASpI dell’1,40% a carico del datore, che sale di 0,50 punti a ogni rinnovo ed e’ restituito se il rapporto viene trasformato.`,
  CONTRACT_TYPES_note_5: 'Contribuzione ordinaria del settore selezionato.',
  CONTRIBUTION_SECTORS_name_1: 'Lavoro domestico',
  CONTRIBUTION_SECTORS_name_2: 'Da 51 a 200 dipendenti',
  CONTRIBUTION_SECTORS_name_3: 'Logistica e trasporto merci',
  CONTRIBUTION_SECTORS_name_4: 'Fino a 50 dipendenti',
  CONTRIBUTION_SECTORS_name_5: 'Pubblici esercizi e turismo',
  CONTRIBUTION_SECTORS_name_6: 'Fino a 50 dipendenti',
  CONTRIBUTION_SECTORS_name_7: 'Commercio e terziario — CUAF ridotta',
  CONTRIBUTION_SECTORS_name_8: 'Da 51 a 200 dipendenti',
  CONTRIBUTION_SECTORS_name_9: 'Fino a 50 dipendenti',
  CONTRIBUTION_SECTORS_name_10: 'Commercio e terziario — CUAF intera',
  CONTRIBUTION_SECTORS_name_11: 'Oltre 50 dipendenti',
  CONTRIBUTION_SECTORS_name_12: 'Da 16 a 50 dipendenti',
  CONTRIBUTION_SECTORS_name_13: 'Fino a 15 dipendenti',
  CONTRIBUTION_SECTORS_name_14: 'Oltre 50 dipendenti',
  CONTRIBUTION_SECTORS_name_15: 'Da 16 a 50 dipendenti',
  CONTRIBUTION_SECTORS_name_16: 'Fino a 15 dipendenti',
  CONTRIBUTION_SECTORS_name_17: 'Industria in genere',
  CONTRIBUTION_SECTORS_note_1: 'La CUAF ridotta spetta ad alcune categorie di datori: va verificata, non assunta.',
  CONTRIBUTION_SECTORS_note_2: 'Nel commercio la tabella non separa operai e impiegati.',
  CONTRIBUTION_SECTORS_note_3: 'Le imprese artigiane non hanno soglie dimensionali per CIGO e CIGS.',
  CONTRIBUTION_SECTORS_note_4: 'Sugli operai edili la CIG ordinaria vale 4,70% e non scende con la dimensione.',
  CONTRIBUTION_SECTORS_source_1: 'Stima parametrica: nel lavoro domestico il contributo è orario, non percentuale',
  CONTRIBUTION_SECTORS_source_2: 'Stima parametrica: le aliquote agricole variano per zona e per tipo di azienda',
  CONTRIBUTION_SECTORS_source_3: 'Tabelle INPS delle aliquote contributive, tab. 7.13, edizione 2026',
  CONTRIBUTION_SECTORS_source_4: 'Tabelle INPS delle aliquote contributive, tab. 7.17, edizione 2026',
  CONTRIBUTION_SECTORS_source_5: 'Tabelle INPS delle aliquote contributive, tab. 7.2, edizione 2026',
  CONTRIBUTION_SECTORS_source_6: 'Tabelle INPS delle aliquote contributive, tab. 7.1 e 7.3, edizione 2026',
  CONTRIBUTION_SECTORS_source_7: 'Tabelle INPS delle aliquote contributive, tab. 4.1, edizione 2026',
  CONTRIBUTION_SECTORS_source_8: 'Tabelle INPS delle aliquote contributive, tab. 1.4-1.6, edizione 2026',
  CONTRIBUTION_SECTORS_source_9: 'Tabelle INPS delle aliquote contributive, tab. 1.1-1.3, edizione 2026',
  contributionsNote_1: (a1, a2) => `, ${a1}% oltre ${a2}`,
  contributionsNote_2: (a1) => `${a1}% sul reddito`,
  contributionsNote_3: (a1, a2) => `${a1}%, fermi al massimale di ${a2}`,
  contributionsNote_4: (a1) => `Calcolati sul minimale di ${a1}, non sul reddito: sotto quella soglia il contributo non scende`,
  csv_1: '"Voce";"Annuo";"Mensile"',
  description_1: (a1) => `Aliquota unica ${a1}%`,
  description_2: 'Nessuna addizionale deliberata',
  employeeExplanations_1: '− detrazione regionale',
  employeeExplanations_2: (a1, a2) => `${a1} × ${a2}% sull’intero`,
  employeeExplanations_3: (a1) => `Esenzione fino a ${a1} di reddito`,
  employeeExplanations_body_1: (a1, a2, a3, a4) => `Entro ${a1} annui e per redditi fino a ${a2}, il premio sconta un'imposta sostitutiva al posto dell'IRPEF: ${a3}% nel ${a4}. Resta però soggetto a contribuzione. Convertirlo in welfare aziendale lo rende esente sia da imposte sia da contributi.`,
  employeeExplanations_body_2: `Il versamento esce interamente dal netto, ma riduce l’imponibile fino a 5.164,57 € l’anno (5.300 € dal 2026). Il tetto è <strong>unico</strong> per il lavoratore e per il datore: se l’azienda versa al fondo, consuma capienza e la quota del lavoratore diventa deducibile solo per la parte restante. Nei fondi negoziali il contributo aziendale spetta soltanto a chi versa la propria quota: chi non aderisce rinuncia a quel denaro.`,
  employeeExplanations_body_3: ' Attenzione: superano un quinto del netto, soglia che la legge pone alla cessione del quinto.',
  employeeExplanations_body_4: `La quota di contributi esonerata non viene versata all’INPS, quindi resta nel netto. Attenzione pero’: cio’ che non si versa resta reddito imponibile, quindi una parte del vantaggio torna allo Stato come IRPEF. L’aliquota di computo ai fini pensionistici resta piena: l’esonero non intacca la pensione futura.`,
  employeeExplanations_body_5: (a1, a2) => `La soglia annua è ${a1}, che sale a ${a2} con figli a carico. Superarla anche di un euro rende imponibile l'intero valore, non la sola eccedenza: è una soglia, non una franchigia.`,
  employeeExplanations_body_6: (a1, a2, a3) => `Nel 2026 le maggiorazioni e le indennità per lavoro notturno, festivo, nei giorni di riposo e a turni scontano un'imposta sostitutiva del ${a1}% al posto dell'IRPEF, fino a ${a2} l'anno, per chi nel 2025 ha avuto un reddito da lavoro dipendente fino a ${a3}. Vale nel settore privato. Gli straordinari ordinari non sono agevolati. La parte oltre il limite torna a tassazione ordinaria. Qui la soglia di reddito si controlla sulla retribuzione dell’anno simulato, part-time compreso. Per bar, ristoranti, turismo e stabilimenti termali la legge esclude questa imposta e prevede invece, dal 1° gennaio al 30 settembre 2026, un trattamento integrativo del 15% su notturno e straordinario festivo: il calcolatore non lo modella e, scegliendo il settore «Pubblici esercizi», tassa le maggiorazioni in modo ordinario.`,
  employeeExplanations_body_7: `Ogni regione delibera le proprie aliquote, e la struttura cambia: alcune applicano un'aliquota unica, altre scaglioni progressivi come l'IRPEF, dove ogni fascia colpisce solo la quota di imponibile che vi ricade. Si calcola per competenza sull'anno, non per cassa: in busta paga viene ripartita sulle mensilità dell'anno successivo.`,
  employeeExplanations_body_8: (a1) => ` Qui è ragguagliato ai ${a1} giorni di rapporto.`,
  employeeExplanations_body_9: (a1, a2) => ` Il rapporto dura ${a1} giorni: la percentuale si sceglie sul reddito rapportato all’anno intero (${a2}) e si applica al reddito del periodo.`,
  employeeExplanations_body_10: (a1) => ` Qui è ragguagliata ai ${a1} giorni di rapporto.`,
  employeeExplanations_body_11: ' Per il 2026 non risulta ancora una delibera pubblicata, quindi resta in vigore l\'aliquota 2025.',
  employeeExplanations_body_12: 'Ogni comune delibera in autonomia aliquota, soglia ed eventuali scaglioni: i valori arrivano dall\'anagrafe ufficiale del MEF.',
  employeeExplanations_body_13: 'Questo comune non prevede soglia di esenzione. ',
  employeeExplanations_body_14: (a1) => `Questo comune esenta i redditi fino a ${a1}. La soglia non è una franchigia: superandola si paga sull'intero imponibile. `,
  employeeExplanations_body_15: 'Le detrazioni non generano credito d\'imposta: la parte eccedente l\'IRPEF lorda si perde. Con un regime agevolato attivo il fenomeno si accentua, perché l\'imposta lorda su cui applicarle è più bassa.',
  employeeExplanations_body_16: 'I regimi agevolati abbattono la base imponibile IRPEF ma non toccano la base contributiva: i contributi restano dovuti sull\'intera retribuzione. È una distinzione che cambia il risultato in modo sostanziale.',
  employeeExplanations_body_17: 'Decresce all\'aumentare del reddito e si azzera a 50.000 € di imponibile.',
  employeeExplanations_body_18: (a1) => `La detrazione annua piena viene ragguagliata ai ${a1} giorni di durata del rapporto: è il criterio dell'art. 13 TUIR, che guarda ai giorni per i quali la detrazione spetta, non alle presenze.`,
  employeeExplanations_body_19: 'Nel 2025 lo scaglione 28.000–50.000 € è tassato al 35%. Dal 2026 la stessa fascia scende al 33%.',
  employeeExplanations_body_20: 'Dal 2026 la seconda aliquota scende dal 35% al 33% sullo scaglione 28.000–50.000 €. Cambia solo quella: la prima resta al 23% e la terza al 43%.',
  employeeExplanations_body_21: (a1, a2) => `Sulla quota di retribuzione che supera la prima fascia pensionabile si versa un ulteriore 1%. È dovuta solo quando l'aliquota a carico del lavoratore è inferiore al 10%, e nel ${a1} la soglia è ${a2}. Pesa solo sulle retribuzioni alte.`,
  employeeExplanations_body_22: (a1) => ` Qui la base è limitata al massimale di ${a1}: oltre quella soglia non si versano più contributi, e il netto marginale sale.`,
  employeeExplanations_body_23: 'L\'aliquota a carico del lavoratore dipende da inquadramento e settore: un apprendista versa il 5,84%, un impiegato il 9,19%, un\'azienda con CIGS il 9,49%.',
  employeeExplanations_body_24: 'La RAL contrattuale vale per un anno intero a tempo pieno. Part-time e durata del rapporto la riducono in proporzione — e con essa detrazioni e cuneo, che sono ragguagliati al periodo. I giorni sono quelli di calendario del rapporto, non le presenze. Le soglie di reddito invece restano quelle annue: non si ragguagliano.',
  employeeExplanations_body_25: (a1) => `Quota sindacale, cessione del quinto, pignoramenti, prestiti aziendali, mensa: escono dal netto già tassato. Non sono oneri deducibili né detraibili, quindi non toccano imponibile, imposte o contributi. La pressione fiscale mostrata sopra le ignora, perché misura il prelievo dello Stato, non le spese personali.${a1}`,
  employeeExplanations_body_26: (a1) => `I 1.200 € annui dell'ex bonus Renzi spettano solo se l'imposta lorda supera la detrazione da lavoro dipendente: è una <strong>condizione di capienza</strong>, non una soglia di reddito. Il punto di pareggio cade intorno a 8.500 € di imponibile — sotto, il contribuente è incapiente e il bonus non spetta. Dedurre troppo, per esempio versando molto al fondo pensione, può farlo perdere.${a1}`,
  employeeExplanations_body_27: (a1) => `Fino a 20.000 € di imponibile il beneficio è una <strong>somma esentasse</strong> che non concorre al reddito: si aggiunge al netto e non erode l'IRPEF, quindi spetta anche a chi è incapiente. Le percentuali sono 7,1% fino a 8.500 €, 5,3% fino a 15.000 €, 4,8% fino a 20.000 €. Oltre i 20.000 € sparisce e subentra l'ulteriore detrazione, che invece la capienza la richiede.${a1}`,
  employeeExplanations_body_28: (a1) => `Sopra i 20.000 € di imponibile il taglio del cuneo cambia natura: non è più una somma esentasse ma una <strong>detrazione d'imposta</strong>, quindi soggetta a capienza. Vale 1.000 € fino a 32.000 € e si azzera progressivamente fino a 40.000 €. Il salto di natura è il motivo per cui intorno ai 20.000 € la curva del netto cambia pendenza.${a1}`,
  employeeExplanations_html_1: 'Imposta sostitutiva',
  employeeExplanations_html_2: 'Premio agevolato',
  employeeExplanations_html_3: 'Totale accantonato nel fondo',
  employeeExplanations_html_4: 'Quota dedotta dall’imponibile',
  employeeExplanations_html_5: 'Contributo del datore',
  employeeExplanations_html_6: 'Versamento del lavoratore',
  employeeExplanations_html_7: 'Netto che arriva sul conto',
  employeeExplanations_html_8: 'Trattenute',
  employeeExplanations_html_9: 'Netto prima delle trattenute',
  employeeExplanations_html_10: 'Contributi effettivi',
  employeeExplanations_html_11: 'Contributi dovuti',
  employeeExplanations_html_12: 'Soglia applicabile',
  employeeExplanations_html_13: 'Valore dei benefit',
  employeeExplanations_html_14: 'Imposta sostitutiva',
  employeeExplanations_html_15: 'Nessuna addizionale dovuta',
  employeeExplanations_html_16: '− taglio di legge',
  employeeExplanations_html_17: 'Detrazione da lavoro',
  employeeExplanations_html_18: 'Detrazione spettante',
  employeeExplanations_html_19: 'Nessuna addizionale dovuta',
  employeeExplanations_html_20: 'Detrazioni spettanti',
  employeeExplanations_html_21: 'Imponibile prima del regime',
  employeeExplanations_html_22: 'Detrazione spettante',
  employeeExplanations_html_23: '× giorni',
  employeeExplanations_html_24: 'Detrazione annua piena',
  employeeExplanations_html_25: (a1, a2) => `<p class="exp-source">Con le aliquote ${a1}: ${a2}</p>`,
  employeeExplanations_html_26: '× giorni',
  employeeExplanations_source_1: 'L. 199/2025, art. 1, commi 10 e 11',
  employeeExplanations_source_2: (a1) => `. Non incluse: ${a1}`,
  employeeExplanations_source_3: 'Aliquote e disposizioni particolari deliberate — MEF, Dipartimento delle Finanze',
  employeeExplanations_source_4: 'D.L. 3/2020 conv. L. 21/2020; L. 207/2024, art. 1, comma 3 (taglio di 75 €)',
  employeeExplanations_source_5: 'L. 207/2024, commi 4, 5 e 9; Agenzia delle Entrate, circolare 4/E del 16/05/2025',
  employeeExplanations_source_6: 'MEF — Dipartimento delle Finanze, anagrafe delle delibere comunali',
  employeeExplanations_source_7: 'D.Lgs. 209/2023 per gli impatriati; art. 44 D.L. 78/2010 per docenti e ricercatori',
  employeeExplanations_source_8: 'Legge di Bilancio 2026',
  employeeExplanations_title_1: 'Premio di risultato',
  employeeExplanations_title_2: 'Altre trattenute',
  employeeExplanations_title_3: 'Esonero contributivo',
  employeeExplanations_title_4: 'Fringe benefit oltre soglia',
  employeeExplanations_title_5: 'Maggiorazioni per notturno, festivo e turni',
  employeeExplanations_title_6: 'Bonus del cuneo fiscale',
  employeeExplanations_title_7: 'Ulteriore detrazione del cuneo fiscale',
  employeeExplanations_title_8: 'Detrazioni perse per incapienza',
  employeeExplanations_title_9: 'Detrazione per lavoro dipendente',
  employeeExplanations_title_10: 'Aliquota aggiuntiva dell\'1%',
  employeeExplanations_title_11: (a1) => `Contributi — ${a1}`,
  exemptionStatus_reason_1: (a1) => `nessun importo definito per il ${a1}`,
  exemptionStatus_reason_2: `riservato alle regioni del Mezzogiorno`,
  exemptionStatus_reason_3: `non spetta per l’inquadramento selezionato`,
  exemptionStatus_reason_4: `non spetta nel settore selezionato`,
  exemptionStatus_reason_5: `non spetta per il rapporto selezionato`,
  exemptionStatus_reason_6: (a1) => `finestra chiusa il ${a1}: non si applica alle assunzioni di oggi`,
  exemptionStatus_reason_7: (a1) => `non ancora in vigore: parte dal ${a1}`,
  FLAT_RATE_COEFFICIENTS_ateco_1: 'tutti i codici non elencati altrove',
  FLAT_RATE_COEFFICIENTS_name_1: 'Attività dei servizi di alloggio e di ristorazione',
  FLAT_RATE_COEFFICIENTS_name_2: 'Commercio ambulante di prodotti alimentari e bevande',
  FLAT_RATE_COEFFICIENTS_name_3: 'Commercio all’ingrosso e al dettaglio',
  FLAT_RATE_COEFFICIENTS_name_4: 'Industrie alimentari e delle bevande',
  FLAT_RATE_COEFFICIENTS_name_5: 'Commercio ambulante di altri prodotti',
  FLAT_RATE_COEFFICIENTS_name_6: 'Intermediari del commercio',
  FLAT_RATE_COEFFICIENTS_name_7: 'Costruzioni e attività immobiliari',
  FLAT_RATE_COEFFICIENTS_name_8: 'Altre attività economiche',
  FLAT_RATE_COEFFICIENTS_name_9: 'Attività professionali, scientifiche, tecniche, sanitarie, di istruzione, servizi finanziari e assicurativi',
  FLAT_RATE_source_1: 'L. 190/2014, art. 1, commi 54-89; allegato 2 alla L. 145/2018',
  foregoneBlock_1: (a1) => `<li class="flex justify-between gap-3"><span>Stesso valore, costo aziendale minore</span>
                   <span class="num font-semibold">− ${a1}</span></li>`,
  foregoneBlock_2: (a1) => `<li class="flex justify-between gap-3"><span>Valore in più a parità di spesa</span>
                   <span class="num font-semibold">+ ${a1}</span></li>`,
  foregoneBlock_3: (a1, a2) => `Pacchetto analizzato: <strong class="text-slate-700">&laquo;${a1}&raquo;</strong>,
        confrontato con <strong class="text-slate-700">&laquo;${a2}&raquo;</strong>`,
  foregoneBlock_4: (a1) => `
      <div class="px-6 py-4 border-t border-slate-200">
        ${a1}
        <p class="text-sm text-slate-600">
          Senza welfare non c'è nulla da confrontare: tutto il valore passa dalla busta paga.
          Nessuna rinuncia su TFR e pensione, ma nemmeno un risparmio per l'azienda.
          Scegli un altro pacchetto per leggere il baratto.
        </p>
      </div>`,
  foregoneBlock_5: (a1, a2, a3, a4, a5, a6, a7) => `
    <div class="px-6 py-4 border-t border-slate-200">
      ${a1}
      <div class="grid sm:grid-cols-2 gap-4">
        <div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4">
          <p class="text-xs font-bold text-emerald-800 uppercase tracking-wider">Guadagna</p>
          <ul class="mt-2 space-y-1.5 text-sm text-emerald-900">
            <li class="flex justify-between gap-3"><span>Welfare esente da imposte</span>
              <span class="num font-semibold">${a2}</span></li>
            ${a3}
          </ul>
        </div>
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-4">
          <p class="text-xs font-bold text-amber-800 uppercase tracking-wider">Rinuncia</p>
          <ul class="mt-2 space-y-1.5 text-sm text-amber-900">
            <li class="flex justify-between gap-3"><span>Retribuzione lorda dichiarata</span>
              <span class="num font-semibold">− ${a4}</span></li>
            <li class="flex justify-between gap-3"><span>TFR maturato nell'anno</span>
              <span class="num font-semibold">− ${a5}</span></li>
            <li class="flex justify-between gap-3"><span>Accantonamento pensionistico</span>
              <span class="num font-semibold">− ${a6}</span></li>
            <li class="text-xs text-amber-800/90 pt-1">
              In tutto <strong>${a7}</strong> l'anno di accantonamenti differiti.
              Cala anche la base per NASpI, malattia e maternità, e il reddito che le banche
              leggono per un mutuo. Il welfare inoltre è vincolato nell'uso.
            </li>
          </ul>
        </div>
      </div>
    </div>`,
  header_1: (a1) => `
    <p class="text-xs font-semibold uppercase tracking-wider text-slate-600">
      Cosa cambia per il lavoratore
    </p>
    <p class="text-xs text-slate-600 mt-0.5 mb-3">${a1}</p>`,
  HIRING_EXEMPTIONS_conditions_1: 'Lavoratrici madri di almeno tre figli con rapporto a tempo indeterminato, fino al compimento dei 18 anni del figlio più piccolo. Il tetto di 3.000 € annui è ripartito su 12 mensilità.',
  HIRING_EXEMPTIONS_conditions_2: 'Datori privati, assunzione a tempo indeterminato o trasformazione, di madri con almeno tre figli under 18 prive di impiego regolarmente retribuito da almeno sei mesi. Personale non dirigenziale, premi INAIL esclusi dall’esonero.',
  HIRING_EXEMPTIONS_conditions_3: 'Personale non dirigenziale assunto a tempo indeterminato nelle aree della ZES unica. Nel 2026 la proroga copriva le sole assunzioni fino al 30 aprile.',
  HIRING_EXEMPTIONS_conditions_4: `Non e’ un incentivo all’assunzione ma alla trasformazione: vale per i passaggi a tempo indeterminato effettuati fra il 1° agosto e il 31 dicembre 2026 di rapporti a termine instaurati entro il 30 aprile 2026, senza soluzione di continuita’ e di durata complessiva non superiore a dodici mesi. Il lavoratore deve avere meno di 35 anni alla trasformazione e non essere mai stato occupato a tempo indeterminato. Ammessi tutti i datori privati, compresi gli agricoli; escluse le pubbliche amministrazioni, il lavoro domestico, l’apprendistato, i dirigenti e la trasformazione del lavoro intermittente. Nel part-time il tetto e’ riproporzionato. Richiesti DURC regolare e incremento occupazionale netto sulla media dei dodici mesi precedenti. I premi INAIL restano dovuti.`,
  HIRING_EXEMPTIONS_conditions_5: 'Under 35 mai assunti a tempo indeterminato. Nel 2026 la proroga copriva le sole assunzioni fino al 30 aprile, con esonero pieno solo in caso di incremento occupazionale netto.',
  HIRING_EXEMPTIONS_conditions_6: 'Assunzione a tempo indeterminato di donne svantaggiate, con incremento occupazionale netto. Durata 24 mesi, ridotti a 12 nei settori con accentuata disparita’ di genere.',
  HIRING_EXEMPTIONS_conditions_7: 'Datori privati con meno di 250 dipendenti, sedi nelle otto regioni del Mezzogiorno. Esclusi agricoltura, lavoro domestico e pubblica amministrazione.',
  HIRING_EXEMPTIONS_description_1: 'Esonero totale della quota di contributi previdenziali a carico della lavoratrice.',
  HIRING_EXEMPTIONS_description_2: 'Esonero totale dei contributi a carico del datore per l’assunzione stabile di madri di almeno tre figli minori.',
  HIRING_EXEMPTIONS_description_3: 'Esonero dei contributi a carico del datore per assunzioni stabili nelle aree della ZES unica.',
  HIRING_EXEMPTIONS_description_4: 'Esonero totale dei contributi a carico del datore per la trasformazione a tempo indeterminato del rapporto a termine di un under 35.',
  HIRING_EXEMPTIONS_description_5: 'Esonero dei contributi a carico del datore per l’assunzione stabile di under 35 mai occupati a tempo indeterminato.',
  HIRING_EXEMPTIONS_description_6: 'Esonero totale dei contributi a carico del datore per l’assunzione a tempo indeterminato di donne svantaggiate.',
  HIRING_EXEMPTIONS_description_7: 'Esonero parziale dei contributi a carico del datore per le piccole e medie imprese del Mezzogiorno.',
  HIRING_EXEMPTIONS_name_1: 'Esonero lavoratrici madri con tre o più figli',
  HIRING_EXEMPTIONS_name_2: 'Esonero per l’assunzione di madri con tre figli',
  HIRING_EXEMPTIONS_name_3: 'Incentivo alla stabilizzazione degli under 35',
  HIRING_EXEMPTIONS_source_1: 'D.L. 60/2024, art. 23 — prorogato per il 2026 dal D.L. 200/2025',
  items_label_1: 'Altre trattenute',
  items_label_2: 'Versamento al fondo pensione',
  items_label_3: 'Imposte sostitutive su premi, maggiorazioni e rinnovi',
  items_label_4: 'Addizionali regionale e comunale',
  items_label_5: 'Contributi INPS',
  items_label_6: 'Netto in busta',
  measure_1: (a1, a2) => `${a1}% fino a ${a2} al mese`,
  measure_2: (a1, a2) => `${a1}% fino a ${a2} l'anno`,
  message_1: (a1, a2, a3) => `Serve una RAL di <strong>${a1}</strong>, che produce ${a2} netti al mese su ${a3} mensilità.`,
  netSteps_1: 'Fatturato',
  notes_1: (a1) => `Il totale è ${a1}: retribuzione maturata, premi e compensi accessori`,
  optimisedPackages_1: 'Aggiunge il premio di risultato erogato in welfare aziendale',
  optimisedPackages_2: 'Con premio convertito',
  optimisedPackages_3: 'Fringe benefit e buoni pasto entro le soglie di esenzione',
  optimisedPackages_4: 'Con welfare esente',
  optimisedPackages_5: 'Tutto il valore passa dalla busta paga',
  optimisedPackages_6: 'Solo retribuzione',
  paintOptimisation_1: 'Valore in più',
  paintOptimisation_2: (a1, a2, a3, a4) => `Con un budget di <strong>${a1}</strong>, il pacchetto a costo minore consegna
             <strong>${a2}</strong> invece di ${a3}:
             <strong class="text-emerald-700">${a4} in più al lavoratore</strong>.`,
  paintOptimisation_3: (a1) => ` <span class="text-amber-700">La cifra esatta non &egrave; raggiungibile per via dei salti normativi:
                    il pacchetto ne consegna ${a1}.</span>`,
  paintOptimisation_4: (a1, a2, a3, a4) => `Per consegnare <strong>${a1}</strong> di valore annuo, il pacchetto a costo minore costa
             <strong>${a2}</strong> invece di ${a3}:
             <strong class="text-emerald-700">${a4} in meno</strong>.`,
  paintOptimisation_5: (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13) => `
    <div class="px-6 py-4 border-b border-slate-200 bg-slate-50">
      <p class="text-sm text-slate-700">
        ${a1}
      </p>
      <p class="text-xs text-slate-600 mt-1">
        Nel pacchetto a costo minore ${a2}% del valore arriva come denaro in busta,
        il resto come welfare vincolato nell'uso.
      </p>
    </div>
    <div class="px-6 pt-4 no-print">
      <p class="text-xs text-slate-600">
        Il pacchetto con il costo minore è già selezionato. <strong class="text-slate-700">Scegline un altro</strong>
        per ricalcolare su quello i due riquadri qui sotto.
      </p>
    </div>
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead class="bg-white text-slate-600 text-xs uppercase tracking-wider border-b border-slate-200">
          <tr>
            <th class="w-8 pl-4 pr-0 py-3"><span class="sr-only">Pacchetto analizzato</span></th>
            <th class="text-left font-semibold px-3 py-3">Pacchetto</th>
            <th class="text-right font-semibold px-3 py-3">RAL</th>
            <th class="text-right font-semibold px-3 py-3">Netto in busta</th>
            <th class="text-right font-semibold px-3 py-3">Welfare</th>
            <th class="text-right font-semibold px-3 py-3">Costo azienda</th>
            <th class="text-right font-semibold px-6 py-3">${a3}</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-slate-100">
          ${a4}
        </tbody>
      </table>
    </div>
    ${a5}
    ${a6}
    <div class="px-6 py-4 border-t border-slate-200">
      <p class="text-xs font-semibold uppercase tracking-wider text-slate-600 mb-2">
        Quanto arriva al lavoratore per ogni euro speso
      </p>
      <div class="flex flex-wrap gap-x-6 gap-y-1 text-xs text-slate-600">
        <span>Retribuzione <strong class="num">${a7} €</strong></span>
        <span>Fringe benefit <strong class="num text-emerald-700">${a8} €</strong></span>
        <span>Buoni pasto <strong class="num text-emerald-700">${a9} €</strong></span>
        <span>Premio in welfare <strong class="num text-emerald-700">${a10} €</strong></span>
        <span>Premio in denaro <strong class="num">${a11} €</strong></span>
      </div>
      <p class="text-[11px] text-slate-600 mt-2">
        Valori ricalcolati, non stimati: a ogni strumento viene aggiunta una quota e si osserva
        la variazione reale di costo e di valore ricevuto.
      </p>
    </div>
    <div class="px-6 py-4 border-t border-slate-200 bg-amber-50">
      <p class="text-xs font-semibold text-amber-900 mb-1.5">Condizioni da verificare prima di proporlo</p>
      <ul class="text-xs text-amber-900/90 space-y-1 list-disc list-inside">
        <li>Il <strong>premio di risultato</strong> richiede un contratto collettivo aziendale o territoriale,
            depositato entro 30 giorni dalla sottoscrizione, e spetta per redditi fino a
            ${a12}. Senza quel contratto il pacchetto non è proponibile,
            qualunque sia il settore.</li>
        <li>I <strong>buoni pasto</strong> presuppongono giornate di presenza effettive: qui ne sono ipotizzate
            ${a13} l'anno.</li>
        <li>La soglia dei <strong>fringe benefit</strong> ha effetto scalino: superarla di un euro rende imponibile
            l'intero importo, quindi il calcolo non la supera mai.</li>
        <li>Il welfare è <strong>vincolato nell'uso</strong> e non costruisce pensione: non è denaro, e la scelta
            va spiegata al lavoratore.</li>
      </ul>
    </div>`,
  PENSION_SCHEMES_name_1: 'Commercianti — gestione INPS',
  PENSION_SCHEMES_name_2: 'Artigiani — gestione INPS',
  PENSION_SCHEMES_name_3: 'Gestione Separata — professionisti',
  PENSION_SCHEMES_note_1: "L'aliquota comprende lo 0,48% per l'indennizzo di cessazione. Minimale come per gli artigiani: 4.611,64 € l'anno anche a reddito zero.",
  PENSION_SCHEMES_note_2: "Contributo dovuto almeno sul minimale (18.808 € nel 2026, 18.555 € nel 2025): nel 2026 sono 4.521,36 € l'anno anche a reddito zero.",
  PENSION_SCHEMES_note_3: "Per chi esercita un'attività senza una cassa professionale di categoria. Sul reddito effettivo: niente minimale, a reddito zero non si versa nulla.",
  PENSION_SCHEMES_source_1: 'INPS, circolare n. 14 del 9 febbraio 2026',
  PENSION_SCHEMES_source_2: 'INPS, circolare n. 38 del 7 febbraio 2025',
  PENSION_SCHEMES_source_3: 'INPS, circolare n. 14 del 9 febbraio 2026',
  PENSION_SCHEMES_source_4: 'INPS, circolare n. 38 del 7 febbraio 2025',
  PENSION_SCHEMES_source_5: 'INPS, circolare n. 8 del 3 febbraio 2026',
  PENSION_SCHEMES_source_6: 'INPS, circolare n. 27 del 30 gennaio 2025',
  readEmployeeParams_daysWorked_1: 'I giorni di rapporto vanno da 1 a 365',
  readEmployeeParams_partTime_1: 'Il part-time va dall’1% al 100%',
  readEmployeeParams_salary_1: 'La RAL va da 0 a 2.000.000 €',
  REGIONAL_TAX_RULES_notIncluded_1: 'l’aliquota ridotta per persone con disabilità o con familiari disabili a carico',
  REGIONAL_TAX_RULES_notIncluded_2: 'la detrazione di 246 € per ogni figlio a carico',
  REGIONAL_TAX_RULES_notIncluded_3: 'le detrazioni per figli minorenni a carico',
  REGIONAL_TAX_RULES_notIncluded_4: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_5: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_6: 'l’aliquota ridotta per chi ha figli con disabilità',
  REGIONAL_TAX_RULES_notIncluded_7: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_8: 'la detrazione di 340 € per ogni figlio a carico',
  REGIONAL_TAX_RULES_notIncluded_9: 'l’aliquota ridotta per persone con disabilità o con familiari disabili a carico',
  REGIONAL_TAX_RULES_notIncluded_10: 'la detrazione di 246 € per ogni figlio a carico',
  REGIONAL_TAX_RULES_notIncluded_11: 'le detrazioni per figli minorenni a carico',
  REGIONAL_TAX_RULES_notIncluded_12: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_13: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_14: 'l’aliquota ridotta per chi ha figli con disabilità',
  REGIONAL_TAX_RULES_notIncluded_15: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_16: 'le detrazioni per figli a carico',
  REGIONAL_TAX_RULES_notIncluded_17: 'la detrazione di 340 € per ogni figlio a carico',
  regionalCases_1: 'oltre 90.000 € resta la sola detrazione da 125 €',
  regionalCases_2: 'più 125 € × (reddito − 50.000) / 25.000',
  regionalCases_3: 'detrazione di 430,50 € fino a 90.000 €',
  regionalCases_4: 'oltre, 1,23% sull’intero',
  regionalCases_5: 'esente fino a 15.000 €',
  regionalCases_6: 'oltre 30.000 € nessuna deduzione',
  regionalCases_7: 'deduzione di 30.000 € fino a 30.000 €',
  regionalCases_8: '1,23% sull’intero oltre 15.000 €',
  regionalCases_9: '0,70% sull’intero fino a 15.000 €',
  regionalCases_10: 'scaglioni meno 150 € fra 28.001 e 50.000 €',
  regionalCases_11: '1,23% sull’intero fino a 28.000 €',
  regionalCases_12: 'nel 2025 la detrazione arrivava a 35.000 €',
  regionalCases_13: 'nel 2026 la detrazione si ferma a 30.000 €',
  regionalCases_14: 'scaglioni meno 60 € fra 28.001 e 30.000 €',
  regionalCases_15: '1,73% sull’intero fino a 28.000 €',
  relevantThresholds_name_1: (a1) => `Esenzione comunale di ${a1}`,
  renderComparison_1: 'Costo azienda',
  renderComparison_2: 'Netto + welfare',
  renderComparison_3: 'Netto annuo',
  renderComparison_4: 'Netto mensile',
  renderComparison_5: 'Aggiorna A',
  renderComparison_6: (a1) => `Scenario <strong class="text-slate-700">A</strong>: ${a1}`,
  renderComparison_7: 'Netto per euro speso',
  renderComparison_8: 'Costo azienda',
  renderComparison_9: 'Tasse e contributi',
  renderComparison_10: 'Netto + welfare',
  renderComparison_11: 'Netto annuo',
  renderComparison_12: 'Netto mensile',
  renderComparison_13: 'Aggiorna A',
  renderComparison_14: 'Blocca come A',
  renderComparison_15: 'Confronta due scenari: blocca questo come <strong class="text-slate-700">A</strong>, poi cambia un parametro e leggi qui la differenza.',
  renderComparison_16: 'Blocca come A',
  renderComparison_17: (a1, a2, a3, a4, a5) => `
    <div class="flex flex-wrap gap-x-6 gap-y-2 text-xs">
      ${a1}
      ${a2}
      ${a3}
      ${a4}
      ${a5}
      <button id="btn-go-comparison" class="text-brand-700 font-semibold hover:underline">tutte le voci ↓</button>
    </div>`,
  renderEmployee_1: (a1, a2, a3) => `
      <tr class="bg-emerald-50">
        <td class="px-6 py-4"><span class="font-extrabold text-emerald-900">Netto in busta pi&ugrave; welfare</span>
          <span class="block text-xs text-emerald-700/70 mt-0.5">Somma di due cose diverse: ${a1} sono welfare vincolato nell&rsquo;uso</span></td>
        <td class="num px-4 py-4 text-right font-extrabold text-emerald-900">${a2}</td>
        <td class="num px-6 py-4 text-right font-extrabold text-emerald-900">${a3}</td>
      </tr>`,
  renderEmployee_2: 'Esente da imposte e contributi',
  renderEmployee_3: 'Premio convertito in welfare',
  renderEmployee_4: (a1) => `Entro ${a1} al giorno`,
  renderEmployee_5: 'Entro la soglia annua',
  renderEmployee_6: (a1, a2, a3) => `
    <tr class="bg-slate-100">
      <td class="px-6 py-4"><span class="font-extrabold text-slate-900">Netto annuo</span>
        <span class="block text-xs text-slate-600 mt-0.5">Su ${a1} mensilit&agrave;</span></td>
      <td class="num px-4 py-4 text-right font-extrabold text-slate-900">${a2}</td>
      <td class="num px-6 py-4 text-right font-extrabold text-slate-900">${a3}</td>
    </tr>`,
  renderEmployee_7: 'Sindacato, cessione del quinto, pignoramenti: nessun effetto fiscale',
  renderEmployee_8: 'Altre trattenute',
  renderEmployee_9: 'Ex bonus Renzi, soggetto a capienza',
  renderEmployee_10: 'Somma esentasse, non erode l&rsquo;IRPEF',
  renderEmployee_11: 'Non transita dalla busta: si accumula nel fondo',
  renderEmployee_12: 'Contributo del datore al fondo',
  renderEmployee_13: 'Quota di contributi non versata: aumenta il netto e l&rsquo;imponibile',
  renderEmployee_14: 'Esonero contributivo della lavoratrice',
  renderEmployee_15: 'Trattenuto in busta paga',
  renderEmployee_16: (a1) => `Trattenuto in busta paga, di cui ${a1} non deducibile`,
  renderEmployee_17: 'Versamento al fondo pensione',
  renderEmployee_18: (a1) => `Aliquota ${a1}%`,
  renderEmployee_19: 'Imposta sostitutiva su maggiorazioni',
  renderEmployee_20: (a1) => `Aliquota ${a1}%`,
  renderEmployee_21: 'Imposta sostitutiva sul premio',
  renderEmployee_22: 'Nessuna aliquota deliberata',
  renderEmployee_23: (a1) => `Esente: imponibile sotto ${a1}`,
  renderEmployee_24: 'A regime, per competenza',
  renderEmployee_25: 'Imposta dovuta',
  renderEmployee_26: 'Eccedenti la capienza IRPEF',
  renderEmployee_27: 'Detrazioni non godute',
  renderEmployee_28: 'Detrazione altri familiari',
  renderEmployee_29: 'Detrazione figli 21+',
  renderEmployee_30: 'Detrazione coniuge a carico',
  renderEmployee_31: 'Imponibile tra 20.000 e 40.000 &euro;',
  renderEmployee_32: 'Ulteriore detrazione (cuneo)',
  renderEmployee_33: ', ragguagliata ai giorni',
  renderEmployee_34: 'Detrazione lavoro dipendente',
  renderEmployee_35: 'Torna a essere reddito imponibile',
  renderEmployee_36: 'Contributo aziendale oltre il tetto',
  renderEmployee_37: (a1) => `Deducibile fino a ${a1}, tetto condiviso con il datore`,
  renderEmployee_38: 'Quota di reddito esclusa da tassazione',
  renderEmployee_39: 'Base al netto dei contributi',
  renderEmployee_40: 'Imponibile fiscale lordo',
  renderEmployee_41: 'Quota del dirigente, deducibile entro il tetto della previdenza complementare',
  renderEmployee_42: 'di categoria',
  renderEmployee_43: (a1) => `Quota oltre ${a1} &mdash; art. 3-ter L. 438/1992`,
  renderEmployee_44: 'Aliquota aggiuntiva 1%',
  renderEmployee_45: (a1) => `Aliquota ${a1} a carico del lavoratore`,
  renderEmployee_46: 'Contributi INPS ordinari',
  renderEmployee_47: 'Non dovuti sull&rsquo;indennit&agrave; di tirocinio',
  renderEmployee_48: 'Contributi previdenziali',
  renderEmployee_49: 'Oltre il limite giornaliero esente',
  renderEmployee_50: 'Soglia superata: intero valore tassato',
  renderEmployee_51: 'Oltre il limite, oltre la soglia di reddito o nel 2025',
  renderEmployee_52: 'Maggiorazioni tassate in modo ordinario',
  renderEmployee_53: (a1, a2) => `Imposta sostitutiva ${a1}% entro ${a2}`,
  renderEmployee_54: 'Premio eccedente il limite',
  renderEmployee_55: (a1) => `Imposta sostitutiva ${a1}%`,
  renderEmployee_56: 'Premio di risultato agevolato',
  renderEmployee_57: (a1) => `${a1} giorni su 365`,
  renderEmployee_58: 'Retribuzione annua a tempo pieno',
  renderEmployee_59: (a1) => ` · ${a1} giorni`,
  renderEmployee_60: (a1, a2, a3, a4, a5) => `${a1} · ${a2} · ${a3} · ${a4} · anno ${a5}`,
  renderEmployee_61: 'accantonato in azienda',
  renderEmployee_62: 'versato al fondo pensione',
  renderEmployee_63: 'non previsto nel tirocinio',
  renderEmployee_64: 'tutto denaro in busta paga',
  renderEmployee_65: (a1) => `${a1} in welfare: vincolato nell'uso, non fa pensione`,
  renderEmployee_66: (a1) => `su ${a1} mensilità`,
  renderEmployee_67: (a1, a2) => `Netto mensile ${a1}, netto annuo ${a2}.`,
  renderEmployee_68: (a1) => `Fondo ${a1}`,
  renderEmployee_body_1: `La retribuzione e i contributi del lavoratore sono valori normativi, calcolabili con precisione. Il costo del datore no: dipende da CCNL, dimensione aziendale e classe di rischio. <strong>Il premio INAIL da solo varia dallo 0,4% a oltre il 13%</strong> secondo la lavorazione: qui è fissato allo 0,5%, valore da ufficio. Per una lavorazione industriale il costo reale è sensibilmente più alto di quanto mostrato. Consideralo un ordine di grandezza, non un preventivo.`,
  renderEmployee_body_2: `<strong>Non è uno stipendio più alto.</strong> È la somma di due cose che non si spendono allo stesso modo: il netto in busta è denaro, il welfare no. Mille euro di buoni pasto valgono mille euro solo per chi quei mille euro li avrebbe spesi comunque in quel modo; non pagano un affitto, non finiscono su un conto, non costruiscono pensione né TFR, e le banche non li leggono come reddito per un mutuo. Il numero serve a confrontare due offerte, non a dire quanto si guadagna: a parità di totale, quella con più denaro in busta è più liquida, quella con più welfare costa meno all'azienda. La barra sotto la cifra mostra la proporzione.`,
  renderEmployee_body_3: `Quanto del lordo non arriva in busta, fra contributi e imposte. Il lordo di riferimento non è solo la RAL: comprende il premio di risultato e i compensi accessori, che sono retribuzione tassata. Restano fuori il welfare esente, che non è reddito, e le altre trattenute — sindacato, prestiti, cessioni — che sono destinazioni dello stipendio, non prelievo: spostano il netto in busta, non la pressione. A redditi bassi può risultare negativa, perché il cuneo restituisce più di quanto il prelievo sottragga.`,
  renderEmployee_html_1: 'Stima del costo annuo',
  renderEmployee_html_2: 'Welfare e benefit',
  renderEmployee_html_3: 'Esonero all’assunzione',
  renderEmployee_html_4: (a1) => `Contributi datore (~${a1})`,
  renderEmployee_html_5: (a1) => `Contributi datore, NASpI inclusa (~${a1})`,
  renderEmployee_html_6: 'Retribuzione e variabili',
  renderEmployee_html_7: 'Welfare esente',
  renderEmployee_html_8: 'Netto in busta',
  renderEmployee_html_9: 'Prelievo sul lordo',
  renderEmployee_html_10: '− netto prima delle trattenute non fiscali',
  renderEmployee_html_11: 'Lordo di riferimento',
  renderEmployee_source_1: 'Aliquote datore: stima parametrica — INAIL: tariffa dei premi per classe di rischio',
  renderEmployee_title_1: 'Costo azienda: perché è una stima',
  renderEmployee_title_2: 'Netto e welfare, sommati',
  renderEmployeeComposition_1: (a1) => `Fuori dalla barra restano ${a1} di welfare esente, che non passa dalla busta paga`,
  renderEmployeeComposition_2: (a1) => `più ${a1} fra bonus del cuneo e trattamento integrativo, che non escono dalla retribuzione ma vi si aggiungono`,
  renderExemptions_1: (a1, a2) => `${a1} e ${a2} non sono cumulabili per legge: il calcolo applica solo il primo dei due.`,
  renderOptimisation_1: (a1) => `Obiettivo netto aggiornato a ${a1} al mese.`,
  renderOptimisation_2: (a1) => `Compilato con il costo del pacchetto a costo minore: ${a1}.`,
  renderOptimisation_3: 'Indica il budget annuo che l’azienda vuole spendere.',
  renderOptimisation_4: 'Indica prima la cifra netta nel riquadro <strong>Dal netto alla RAL</strong>.',
  renderWarnings_1: 'Il comune non ha ancora deliberato per il 2026: resta in vigore l’aliquota 2025.',
  renderWarnings_2: (a1) => `${a1} di detrazioni perse per incapienza: non generano credito d'imposta.`,
  renderWarnings_3: 'Le trattenute superano la retribuzione in denaro: il cedolino risulterebbe incapiente. Succede quando i versamenti volontari eccedono il netto disponibile.',
  renderWarnings_4: (a1, a2) => `Il versamento richiesto al fondo supera quanto la busta paga contiene: trattenuti ${a1} invece di ${a2}.`,
  renderWarnings_5: (a1, a2) => `Le trattenute richieste superano il netto disponibile: applicati ${a1} invece di ${a2}.`,
  renderWarnings_6: (a1) => `I giorni con buono sono stati ridotti a ${a1}: non possono superare i giorni di durata del rapporto.`,
  renderWarnings_7: (a1) => `Il valore imponibile di welfare e compensi supera la retribuzione maturata: mancano ${a1} da cui trattenere imposte e contributi. Una busta paga non va in rosso, quindi il netto si ferma a zero: in azienda quella parte verrebbe recuperata a conguaglio. Controlla la durata del rapporto e i giorni con buono.`,
  renderWarnings_8: (a1) => `Retribuzione mensile sotto il minimale contributivo INPS (${a1}). In busta paga i contributi andrebbero calcolati sul minimale, non sulla retribuzione effettiva: questo calcolo <strong>non</strong> applica la correzione, quindi qui i contributi sono sottostimati.`,
  renderWarnings_9: (a1) => `Aliquota aggiuntiva 1% attiva sulla quota oltre ${a1}.`,
  renderWarnings_10: (a1, a2) => `Massimale contributivo ${a1} raggiunto (${a2}): la contribuzione si ferma, il netto marginale sale.`,
  renderWarnings_11: (a1, a2) => `La retribuzione supera il massimale contributivo ${a1} (${a2}), ma il massimale non è applicato: è corretto solo se hai contributi versati prima del 1996. Per chi ha cominciato dal 1996 in poi i contributi si fermano al massimale e il netto è più alto.`,
  renderWarnings_12: `Indennit&agrave; di tirocinio: &egrave; reddito assimilato al lavoro dipendente (art. 50, comma 1, lett. c TUIR). Nessun contributo previdenziale, nessun TFR, nessuna mensilit&agrave; aggiuntiva. Spettano la detrazione dell&rsquo;art. 13 e il trattamento integrativo; il taglio del cuneo no, perch&eacute; si rivolge ai soli titolari di reddito di lavoro dipendente.`,
  renderWarnings_13: `<p class="text-amber-900">Senza una retribuzione non esiste un rapporto di lavoro da simulare: welfare e compensi accessori sono stati ignorati. Inserisci una RAL.</p>`,
  ROLES_viaggiatore_1: 'Viaggiatore o piazzista',
  row_1: (a1) => `<span class="block text-xs text-amber-700 mt-1">Il premio agevolato non spetta oltre ${a1} di reddito: questo pacchetto non è applicabile.</span>`,
  rows_1: 'Corrispettivi incassati nell’anno, IVA esclusa',
  rows_2: 'Fatturato',
  runTests_1: 'Anno 2025 con input 0 gestito senza NaN',
  runTests_2: 'Artigiani: minimale dell’anno scelto (4.460,64 € nel 2025, 4.521,36 € nel 2026)',
  runTests_3: (a1, a2) => `riferimento ${a1} · detrazione ${a2}`,
  runTests_4: 'Cuneo impatriati: la quota esente conta per le soglie (L. 207/2024, comma 9)',
  runTests_5: 'Cuneo: percentuale sul reddito annualizzato, applicata al reddito del periodo, una volta sola',
  runTests_6: (a1) => `${a1} aliquote oltre lo 0,80% ordinario`,
  runTests_7: 'Dataset: nessuna aliquota comunale oltre il massimo di legge 1,20%',
  runTests_8: 'Dataset: Milano 0,80% con esenzione 23.000 € in entrambi gli anni',
  runTests_9: 'Dataset: anagrafe, tariffe e regioni coerenti fra loro',
  runTests_10: (a1, a2) => `impronta ${a1}, attesa ${a2}: il motore è cambiato, aggiorna ENGINE_VERSION e ENGINE_FINGERPRINT`,
  runTests_11: (a1) => `Versione: l'impronta del motore corrisponde alla v${a1}`,
  runTests_12: 'Gestioni INPS: cambiare gestione cambia il netto',
  runTests_13: 'Partita IVA: fatturato − costi − contributi − imposte + scoperto = netto',
  runTests_14: (a1, a2, a3, a4, a5) => `${a1}/${a2} a ${a3}: ${a4} contro ${a5}`,
  runTests_15: 'Partita IVA: nessuno scoperto quando il fatturato copre i contributi',
  runTests_16: 'Partita IVA: sotto il minimale il netto si ferma a zero e lo scoperto è dichiarato',
  runTests_17: 'Gestioni INPS: la riduzione non tocca il contributo di maternità',
  runTests_18: 'Gestioni INPS: la riduzione del 35% vale solo nel forfetario',
  runTests_19: 'Gestioni INPS: oltre 56.224 € l’aliquota sale di un punto',
  runTests_20: 'Gestioni INPS: a reddito zero il minimale resta dovuto, la Separata no',
  runTests_21: (a1, a2) => `${a1} → ${a2} di imposte`,
  runTests_22: 'Ordinario: i costi abbattono reddito, contributi e imposte',
  runTests_23: 'Partita IVA: detrazione dell’art. 13 commi 5 e 5-ter, non quella dei dipendenti',
  runTests_24: 'Partita IVA: i contributi si fermano al massimale della Gestione separata',
  runTests_25: (a1, a2) => `ordinario: ${a1} a Milano, ${a2} a Roma`,
  runTests_26: 'Forfetario: niente addizionali, il comune non cambia il netto',
  runTests_27: (a1) => `+${a1} rispetto al 15%`,
  runTests_28: 'Forfetario 5%: stessa base, imposta ridotta a un terzo',
  runTests_29: 'Forfetario: coefficiente ATECO, contributi dedotti, 15% sul resto',
  runTests_30: 'Inversione: dichiara le richieste fuori scala',
  runTests_31: 'Inversione: più RAL per lo stesso netto, sceglie la meno costosa',
  runTests_32: 'Inversione: la RAL trovata riproduce il netto richiesto',
  runTests_33: 'Ogni provincia è associata a una regione esistente',
  runTests_34: 'Sweep su tutte le combinazioni di contratto e regime',
  runTests_35: 'Senza retribuzione il netto resta a zero, non va sotto',
  runTests_36: 'Esoneri: le misure non cumulabili sono riconosciute',
  runTests_37: 'Esoneri: l’esclusione regge sulla chiave composta del profilo',
  runTests_38: 'Esoneri: la stabilizzazione esclude dirigenti e rapporti non stabilizzati',
  runTests_39: (a1) => `${a1} di contributi non versati`,
  runTests_40: 'Esoneri: la stabilizzazione vale 500 € al mese dentro la sua finestra',
  runTests_41: 'Co.co.co.: il massimale di 122.295 € si applica da solo',
  runTests_42: 'Co.co.co.: niente TFR né cuneo, il trattamento integrativo resta',
  runTests_43: 'Co.co.co.: 35,03% diviso un terzo e due terzi',
  runTests_44: 'Esoneri: la decontribuzione Sud vale solo nelle regioni previste',
  runTests_45: (a1, a2) => `+${a1} netti su ${a2} esonerati`,
  runTests_46: 'Esoneri: quello della lavoratrice alza netto e imponibile',
  runTests_47: (a1, a2) => `costo ${a1} → ${a2}`,
  runTests_48: 'Esoneri: quello del datore riduce il costo, non il netto',
  runTests_49: (a1) => `finestra chiusa il ${a1}`,
  runTests_50: 'Esoneri: una misura scaduta non viene applicata',
  runTests_51: 'Profili storici: le chiavi dei vecchi link restano valide',
  runTests_52: 'Il netto non scende mai sotto zero, e lo scoperto viene dichiarato',
  runTests_53: (a1, a2) => `${a1} giorni, ${a2} di buoni`,
  runTests_54: 'Buoni pasto: i giorni con buono non superano i giorni di rapporto',
  runTests_55: 'Composizione: le voci della barra sommano esattamente il lordo in busta',
  runTests_56: 'Aliquote per settore: la quota del datore è il totale meno quella del lavoratore',
  runTests_57: 'Aliquote per settore: la somma delle voci torna al totale di tabella',
  runTests_58: (a1, a2, a3) => `${a1}: voci ${a2} contro totale ${a3}`,
  runTests_59: 'Soglie: lo spostamento porta l’imponibile sotto la soglia in ogni profilo',
  runTests_60: (a1, a2, a3) => `${a1}: imponibile ${a2} contro soglia ${a3}`,
  runTests_61: 'premio applicabile',
  runTests_62: 'ricostruito senza premio',
  runTests_63: 'Ottimizzazione: nessun premio promesso oltre la soglia di reddito',
  runTests_64: 'nessuna occasione',
  runTests_65: 'Soglie: anche il gradino del cuneo a 8.500 € è un’occasione misurata',
  runTests_66: 'Soglie: nessun suggerimento se l’imponibile è già basso',
  runTests_67: 'nessuna occasione',
  runTests_68: 'Soglie: individua il gradino raggiungibile e lo quantifica',
  runTests_69: (a1) => `${a1} l'anno di accantonamenti differiti`,
  runTests_70: 'Welfare: quantifica TFR e pensione a cui si rinuncia',
  runTests_71: 'Tirocinio: il trattamento integrativo spetta (circolare 4/E/2025)',
  runTests_72: (a1) => `il dipendente riceve ${a1} di cuneo, il tirocinante nulla`,
  runTests_73: 'Tirocinio: niente cuneo, che è solo per il lavoro dipendente',
  runTests_74: (a1, a2) => `imponibile ${a1}, costo ${a2}`,
  runTests_75: 'Tirocinio: nessun contributo, nessun TFR, imponibile pieno',
  runTests_76: 'Apprendistato: aliquota 5,84% indipendente dal settore',
  runTests_77: (a1) => `+${a1} per l'azienda`,
  runTests_78: 'Tempo determinato: NASpI 1,40% sul solo costo azienda',
  runTests_79: (a1) => `retribuzione ${a1} € per euro speso`,
  runTests_80: 'Efficienza misurata: welfare esente 1:1, retribuzione molto meno',
  runTests_81: 'Ottimizzazione: il welfare resta entro i tetti di legge',
  runTests_82: (a1) => `+${a1} al lavoratore`,
  runTests_83: 'Ottimizzazione dal netto: stesso valore, costo decrescente',
  runTests_84: 'Altre trattenute: non superano il netto disponibile',
  runTests_85: (a1) => `netto ${a1}, pressione invariata`,
  runTests_86: 'Altre trattenute: escono dal netto senza toccare le imposte',
  runTests_87: 'Sweep sulle combinazioni di previdenza complementare',
  runTests_88: 'Fondo: il versamento non supera quanto la busta contiene',
  runTests_89: 'TFR al fondo: nessun contributo dello 0,50% al Fondo di garanzia',
  runTests_90: 'Fondo: il contributo aziendale oltre il tetto torna imponibile',
  runTests_91: (a1, a2) => `dedotti ${a1} su ${a2} versati`,
  runTests_92: 'Fondo: tetto di deducibilità condiviso fra lavoratore e datore',
  runTests_93: (a1) => `chi non aderisce rinuncia a ${a1}`,
  runTests_94: 'Fondo: il contributo del datore spetta solo a chi versa',
  runTests_95: ' tassati in modo ordinario',
  runTests_96: 'Maggiorazioni: niente agevolazione oltre 40.000 € di reddito',
  runTests_97: (a1, a2) => `2025 ordinarie · 2026 agevolate ${a1}, imposta ${a2}`,
  runTests_98: 'Maggiorazioni notturno/festivo/turni: 15% solo nel 2026 ed entro 1.500 €',
  runTests_99: (a1) => `detrazione ${a1} in entrambi i casi`,
  runTests_100: 'Fondo pensione: deduce l’imposta, non gonfia le detrazioni',
  runTests_101: 'Fringe benefit: superata la soglia è tassato tutto',
  runTests_102: 'Ragguaglio ai giorni su retribuzione e detrazioni',
  runTests_103: 'Impatriati: abbatte l’IRPEF ma non i contributi',
  runTests_104: 'Massimale contributivo blocca la contribuzione',
  runTests_105: 'Aliquota aggiuntiva 1% applicata sopra soglia',
  runTests_106: '2026 più conveniente del 2025 nello scaglione 28k–50k',
  runTests_107: 'Sopra la prima fascia pensionabile: aliquota aggiuntiva 1% sull’eccedenza',
  runTests_108: 'Correttivo di fascia: 65 € interi, non rapportati ai giorni',
  runTests_109: (a1, a2) => `${a1} · a termine ${a2}`,
  runTests_110: 'Detrazione art. 13: il pavimento regge al ragguaglio ai giorni',
  runTests_111: (a1, a2) => `detrazioni 12+13 ${a1} vs lorda ${a2}`,
  runTests_112: 'Trattamento integrativo: l’ulteriore detrazione del cuneo non conta',
  runTests_113: (a1) => `pareggio a ${a1} di imponibile`,
  runTests_114: 'Trattamento integrativo: il pareggio è la detrazione meno 75 €',
  runTests_115: 'Trattamento integrativo nullo in caso di incapienza',
  runTests_116: 'Cuneo: bonus esentasse fino a 20.000 € di imponibile',
  runTests_117: 'Quadratura: RAL − trattenute + bonus = netto',
  runTests_118: ' di imponibile',
  runTests_119: 'Monotonicità: rotture solo sulle 4 soglie normative note',
  runTests_120: 'Milano — 0,80% sull’intero imponibile sopra soglia',
  runTests_121: 'Milano — esenzione sotto 23.000 € di imponibile',
  runTests_122: 'RAL 30.000 — netto annuo = 23.425,52 €',
  SELF_EMPLOYED_REGIMES_name_1: 'Regime ordinario',
  SELF_EMPLOYED_REGIMES_note_1: 'Stessa struttura del forfetario ordinario con aliquota al 5%, riservata ai primi cinque anni di una nuova attività.',
  SELF_EMPLOYED_REGIMES_note_2: 'Imposta sostitutiva del 15% al posto di IRPEF, addizionali e IRAP. Il reddito è il fatturato per il coefficiente ATECO: i costi effettivi non si deducono.',
  SELF_EMPLOYED_REGIMES_note_3: 'IRPEF a scaglioni sul reddito al netto dei costi e dei contributi, con addizionali regionale e comunale e detrazione dell’art. 13, comma 5, TUIR.',
  selfEmployedExplanations_1: '+ scoperto non coperto dal fatturato',
  selfEmployedExplanations_2: '− imposte',
  selfEmployedExplanations_3: '− contributi',
  selfEmployedExplanations_body_1: `Quanta parte del fatturato, al netto dei costi, se ne va fra previdenza e fisco. Non è confrontabile con la pressione fiscale di un dipendente: là il datore versa due terzi dei contributi e la cifra di partenza è la RAL, qui la contribuzione è tutta a carico di chi fattura.`,
  selfEmployedExplanations_body_2: ` Qui il fatturato non copre il minimale contributivo: il netto si ferma a zero e la parte scoperta resta un debito verso l’INPS, non un guadagno mancato.`,
  selfEmployedExplanations_body_3: `È quella dell’art. 13, comma 5, del TUIR, non quella dei dipendenti del comma 1: più bassa, e non cumulabile con essa. Non spettano nemmeno il trattamento integrativo e il taglio del cuneo, che si rivolgono ai titolari di reddito di lavoro dipendente. È la ragione per cui, a parità di imponibile, un autonomo in regime ordinario paga più di un dipendente.`,
  selfEmployedExplanations_body_4: 'Gli stessi scaglioni del lavoro dipendente: cambia la base su cui si applicano, non la tariffa. ',
  selfEmployedExplanations_body_5: `Un’unica imposta prende il posto di IRPEF, addizionale regionale, addizionale comunale e IRAP. Nessuno scaglione e nessuna detrazione: un’aliquota piatta sull’imponibile. Il 5% è riservato ai primi cinque anni di una nuova attività, a condizioni che questo calcolatore non verifica.`,
  selfEmployedExplanations_body_6: `I contributi previdenziali sono interamente deducibili: si tolgono dal reddito prima di calcolare l’imposta. È il motivo per cui una contribuzione alta si ripaga in parte da sola, abbassando l’imposta dovuta sullo stesso reddito.`,
  selfEmployedExplanations_body_7: `È una facoltà dei forfetari iscritti alle gestioni artigiani e commercianti, e va chiesta all’INPS: non si applica da sola. Non è denaro regalato: l’accredito pensionistico si riduce nella stessa proporzione, quindi si versa meno oggi e si matura meno domani. Il taglio riguarda la sola quota previdenziale: il contributo di maternità resta dovuto per intero, quindi lo sconto sul totale versato è poco meno del 35%.`,
  selfEmployedExplanations_body_8: ' Oltre il massimale la contribuzione si ferma: il reddito eccedente non versa e non accredita.',
  selfEmployedExplanations_body_9: ` In questo scenario il reddito è sotto il minimale della gestione: il contributo non scende sotto quella soglia, e resta dovuto anche a reddito zero.`,
  selfEmployedExplanations_body_10: `Nell’ordinario il reddito è quello effettivo: fatturato meno costi documentati. È la base sia dei contributi sia delle imposte, e da qui in avanti i due calcoli si intrecciano, perché i contributi sono deducibili.`,
  selfEmployedExplanations_body_11: `Nel forfetario il reddito non si misura: si presume. Al fatturato si applica il coefficiente di redditività del proprio codice ATECO, e quella percentuale <em>è</em> il reddito, qualunque cifra dicano le spese effettive. Chi ha costi bassi ci guadagna, chi ne ha molti ci perde: la convenienza del regime si decide qui, prima ancora delle aliquote.`,
  selfEmployedExplanations_body_12: (a1) => `Quello che resta dopo contributi e imposte. Non è uno stipendio: non ci sono TFR, mensilità aggiuntive, ferie retribuite né malattia pagata, e l’imposta si versa per acconti e saldo, con una cassa che questo calcolatore non simula.${a1}`,
  selfEmployedExplanations_body_13: (a1, a2) => `Chi lavora in proprio versa da solo tutta la contribuzione: non c’è un datore che ne paghi due terzi. E l’ordine è inverso rispetto alla busta paga: qui i contributi si calcolano sul reddito e vengono poi dedotti dall’imponibile fiscale, mentre in busta paga si tolgono dalla RAL per ottenere l’imponibile.${a1}${a2}`,
  selfEmployedExplanations_html_1: 'Contributi + imposte',
  selfEmployedExplanations_html_2: 'Base di calcolo',
  selfEmployedExplanations_html_3: 'Netto annuo',
  selfEmployedExplanations_html_4: '− detrazione spettante',
  selfEmployedExplanations_html_5: 'Imposta sostitutiva',
  selfEmployedExplanations_html_6: '× aliquota',
  selfEmployedExplanations_html_7: '− contributi dedotti',
  selfEmployedExplanations_html_8: 'Reddito',
  selfEmployedExplanations_html_9: 'Contributi versati',
  selfEmployedExplanations_html_10: '− 35% sulla quota previdenziale',
  selfEmployedExplanations_html_11: 'Contributi pieni',
  selfEmployedExplanations_html_12: 'Contributi dovuti',
  selfEmployedExplanations_html_13: 'Aliquota',
  selfEmployedExplanations_html_14: 'Base applicata: il maggiore dei due',
  selfEmployedExplanations_html_15: 'Minimale della gestione',
  selfEmployedExplanations_html_16: 'Reddito',
  selfEmployedExplanations_html_17: 'Reddito',
  selfEmployedExplanations_html_18: 'Fatturato',
  selfEmployedExplanations_html_19: 'Reddito imponibile',
  selfEmployedExplanations_html_20: 'Fatturato',
  selfEmployedExplanations_title_1: 'Prelievo fra contributi e imposte',
  selfEmployedExplanations_title_2: 'Netto',
  selfEmployedExplanations_title_3: 'Detrazione da lavoro autonomo',
  selfEmployedExplanations_title_4: 'Imposta sostitutiva',
  selfEmployedExplanations_title_5: 'Riduzione contributiva del 35%',
  selfEmployedExplanations_title_6: 'Contributi previdenziali',
  selfEmployedExplanations_title_7: 'Reddito d’impresa o di lavoro autonomo',
  selfEmployedExplanations_title_8: 'Reddito imponibile forfetario',
  SEPARATE_SCHEME_source_1: 'INPS circolare n. 8 del 3 febbraio 2026',
  summary_1: 'a scaglioni',
  summary_2: 'nessuna aliquota',
  TAX_REGIMES_name_1: 'Docenti e ricercatori — art. 44 D.L. 78/2010',
  TAX_REGIMES_name_2: 'Nessuna agevolazione',
  thresholds_name_1: 'Terza aliquota IRPEF',
  thresholds_name_2: 'Seconda aliquota IRPEF',
  thresholds_name_3: 'Correttivo di fascia',
  thresholds_name_4: 'Bonus del cuneo fiscale',
  thresholds_name_5: 'Prima fascia del bonus del cuneo',
  thresholds_name_6: 'Accesso ai premi agevolati',
  thresholdsBlock_1: 'È un cambio di aliquota marginale: il vantaggio riguarda solo la quota eccedente.',
  thresholdsBlock_2: 'È un gradino: superata la soglia il beneficio si perde per intero, non in proporzione.',
  thresholdsBlock_3: (a1, a2, a3, a4, a5) => `
      <div class="px-6 py-4 border-t border-slate-200 bg-slate-50">
        <p class="text-xs font-semibold uppercase tracking-wider text-slate-600">
          Soglia raggiungibile
        </p>
        <p class="text-sm text-slate-600 mt-1.5">
          La soglia <strong>${a1}</strong> (${a2}) chiederebbe
          <strong>${a3}</strong> di welfare: con
          <strong>&laquo;${a4}&raquo;</strong> ne sono disponibili ${a5}, e resta fuori portata.
          Un pacchetto con più welfare la riporta a tiro.
        </p>
      </div>`,
  thresholdsBlock_4: (a1, a2, a3, a4, a5, a6, a7, a8) => `
    <div class="px-6 py-4 border-t border-slate-200 bg-brand-50/50">
      <p class="text-xs font-semibold uppercase tracking-wider text-brand-700">
        Soglia raggiungibile
      </p>
      <p class="text-xs text-brand-800 mt-0.5 mb-2">
        Con il welfare di <strong>&laquo;${a1}&raquo;</strong>: ${a2} spostabili
      </p>
      <p class="text-sm text-slate-700">
        L'imponibile attuale supera la soglia <strong>${a3}</strong>
        (${a4}). Con <strong>${a5}</strong> in welfare
        al posto di altrettanta retribuzione, l'imponibile scenderebbe a ${a6} e
        il lavoratore recupererebbe <strong class="text-emerald-700">${a7}</strong> l'anno,
        oltre al vantaggio già calcolato sopra.
      </p>
      <p class="text-[11px] text-slate-600 mt-1.5">
        ${a8}
      </p>
    </div>`,
  top_1: 'non esiste un valore superiore raggiungibile.',
  top_2: (a1, a2) => `sopra è ${a1} al mese con RAL ${a2}.`,
  top_3: ' e da ',
  top_4: (a1, a2) => `Nemmeno ${a1} di RAL producono quella cifra: il massimo raggiungibile con questi parametri è ${a2} al mese.`,
  top_5: 'Inserisci la cifra netta che vuoi ottenere.',
  top_6: 'Copia non riuscita',
  top_7: (a1, a2, a3, a4) => `<strong>Nessuna RAL produce esattamente questa cifra.</strong> Qui il netto fa un salto in avanti: superata una soglia di legge (per esempio quella del trattamento integrativo) aumenta di colpo di ${a1} l'anno, e le cifre in mezzo non le produce nessuna RAL. Il valore più vicino sotto è ${a2} al mese con RAL ${a3}; ${a4}`,
  top_8: (a1, a2) => `<br><br>Attenzione: per via dei salti normativi questa cifra netta è prodotta anche da ${a1}. Ho scelto la più bassa: stesso netto in busta, ma ${a2} in meno di costo azienda.`,
  updateContextNotes_1: 'Nei fondi negoziali il contributo aziendale spetta solo se il lavoratore versa la propria quota.',
  updateContextNotes_2: (a1) => `Spetta perché il lavoratore versa: ${a1} l'anno a carico azienda.`,
  updateContextNotes_3: (a1) => `Supera un quinto del netto: se si tratta di cessione del quinto, la legge non consente di andare oltre ${a1} l’anno.`,
  updateContextNotes_4: ' · nessuna variazione pubblicata per il 2026: vale l’aliquota precedente, finché il comune non delibera',
  updateContextNotes_5: (a1) => ` · esenzione fino a ${a1}`,
  updateContextNotes_6: (a1) => `. Non incluse: ${a1}.`,
  updateContextNotes_7: ' · con le disposizioni particolari della regione',
  updateContextNotes_8: (a1) => `Aliquota unica ${a1}%`,
  updateContextNotes_9: (a1, a2, a3) => `Imposta sostitutiva ${a1}% nel ${a2}, fino a ${a3}.`,
  updateContextNotes_10: (a1) => `Reddito oltre ${a1}: nessuna agevolazione, tassazione ordinaria.`,
  updateContextNotes_11: (a1, a2) => `— esenti fino a ${a1}/giorno nel ${a2}`,
  updateContextNotes_12: ' (con figli a carico)',
  updateContextNotes_13: (a1) => `Soglia di ${a1} superata: l'intero importo è imponibile.`,
  updateContextNotes_14: 'Stima parametrica. ',
  updateContextNotes_15: 'Compenso annuo pattuito',
  updateContextNotes_16: (a1, a2) => `Esenti fino a ${a1}${a2}.`,
  updateContextNotes_17: (a1, a2, a3, a4, a5, a6, a7, a8, a9) => `
    <div class="flex items-baseline justify-between gap-3">
      <span class="text-xs font-semibold text-slate-600">Aliquota contributiva</span>
      <span class="num text-sm font-bold text-slate-900">${a1}%</span>
    </div>
    <div class="flex flex-wrap gap-x-4 text-[11px] text-slate-600 mt-0.5">
      <span>lavoratore <strong class="num text-slate-700">${a2}</strong></span>
      <span>azienda <strong class="num text-slate-700">${a3}</strong></span>
      ${a4}
    </div>
    ${a5}
    <p class="text-[11px] ${a6} mt-2">
      ${a7}${a8}${a9}
    </p>`,
  updateContextNotes_frontalieri_1: (a1) => `Franchigia di ${a1} sul reddito imponibile. Calcolo semplificato: contributi e imposte del paese in cui si lavora, e le regole proprie dei frontalieri in Svizzera, non sono considerati.`,
  updateContextNotes_impatriati_1: (a1, a2) => `Imponibile al ${a1}%, entro ${a2} di reddito agevolabile.`,
  updateContextNotes_nessuno_1: "Le agevolazioni riducono l'imponibile IRPEF, mai la base contributiva.",
  updateContextNotes_ricercatori_1: 'Imponibile al 10% del reddito da lavoro dipendente.',
  updateSelfEmployed_1: (a1, a2) => `Con questo fatturato l’anno si chiude in perdita: contributi e imposte superano di ${a1} quanto resta del fatturato. Il minimale di ${a2} è dovuto comunque, anche a reddito zero.`,
  updateSelfEmployed_2: `L’aliquota del 5% vale solo per i primi cinque anni di una nuova attività, e a condizione che non sia la prosecuzione di un’attività già svolta.`,
  updateSelfEmployed_3: `Il netto più alto risulta dal forfetario al 5%, che però spetta solo a chi avvia una nuova attività e ne ha i requisiti: la tabella confronta i numeri, non verifica se puoi accedere a ciascun regime. La scelta del regime va fatta con un commercialista.`,
  updateSelfEmployed_4: (a1, a2) => `Con ${a1} di ricavi si supera la soglia di ${a2}: il forfetario non si può più applicare dall’anno successivo, e oltre 100.000 € si esce subito, già nell’anno in cui si supera la soglia (L. 190/2014, art. 1, comma 71). Il requisito si misura sui ricavi dell’anno precedente: qui il calcolo resta un confronto teorico.`,
  updateSelfEmployed_5: '<span class="ml-1 text-[10px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded bg-emerald-100 text-emerald-700">netto più alto con questi dati</span>',
  updateSelfEmployed_6: (a1) => `Il minimale di ${a1} è dovuto anche sotto quel reddito: questa quota non è coperta dal fatturato`,
  updateSelfEmployed_7: 'Scoperto a carico dell’iscritto',
  updateSelfEmployed_8: 'Quanto resta dopo contributi e imposte',
  updateSelfEmployed_9: 'Netto',
  updateSelfEmployed_10: 'Art. 13, comma 5, TUIR: più bassa di quella dei dipendenti',
  updateSelfEmployed_11: 'Detrazione da lavoro autonomo',
  updateSelfEmployed_12: (a1) => `${a1}% al posto di IRPEF, addizionali e IRAP`,
  updateSelfEmployed_13: 'Imposta sostitutiva',
  updateSelfEmployed_14: 'Reddito al netto dei contributi, che sono deducibili',
  updateSelfEmployed_15: 'Già applicata sopra: abbassa anche l’accredito ai fini pensionistici',
  updateSelfEmployed_16: 'Riduzione contributiva del 35%',
  updateSelfEmployed_17: (a1) => `Contributi — ${a1}`,
  updateSelfEmployed_18: 'Base su cui si calcolano contributi e imposte',
  updateSelfEmployed_19: 'Reddito d’impresa o di lavoro autonomo',
  updateSelfEmployed_20: (a1) => `Fatturato × ${a1}%: i costi effettivi non entrano nel calcolo`,
  updateSelfEmployed_21: 'Reddito imponibile forfetario',
  updateSelfEmployed_22: 'Spese effettive dell’attività',
  updateSelfEmployed_23: (a1, a2) => `${a1} · anno ${a2} · importi annui e mensili`,
  updateSelfEmployed_24: (a1) => `${a1}% fra contributi e imposte`,
  updateSelfEmployed_25: (a1, a2) => `Netto mensile ${a1}, netto annuo ${a2}.`,
  updateSelfEmployed_26: 'Importo al netto dell’IVA.',
  updateSelfEmployed_27: (a1) => `Soglia del regime forfetario: ${a1} di ricavi nell’anno precedente.`,
  updateSelfEmployed_28: (a1) => `Addizionale comunale di ${a1}, la stessa scelta nella scheda «Dipendente».`,
  updateSelfEmployed_29: 'Nel forfetario l’imposta sostitutiva prende il posto delle addizionali: il comune non incide.',
  updateSelfEmployed_30: (a1, a2) => `Codici ATECO 2007 ${a1} — imponibile ${a2}% del fatturato`,
  updateSelfEmployed_31: ` <strong class="text-amber-700">Il reddito è sotto il minimale: i contributi restano quelli del minimale, non scendono.</strong>`,
  analysePackageLabel: (name) => `Analizza il pacchetto ${name}`,
  chartAriaLabel: 'Curva del netto annuo al variare della RAL',
  explanationButtonLabel: (title) => `Come è stato calcolato: ${title}`,
  referenceLabel: 'riferimento',
  testChildrenDeductionSplit: 'Detrazione figli divisa al 50% fra i genitori, salvo accordo o coniuge a carico',
  testFamilyDeductionsByMonth: 'Detrazioni familiari per mesi a carico, non per giorni lavorati',
  testFringeMinorChildren: 'Fringe benefit: soglia di 2.000 € anche con figli minorenni a carico',
  testSelfEmployedDeductionBase: 'Partita IVA ordinaria: detrazione dell’art. 13 sul reddito prima dei contributi',
  testPensionCapByYear: 'Previdenza complementare: tetto di 5.164,57 € nel 2025 e di 5.300 € dal 2026',
  testPrevindaiCap: 'Dirigenti: Previndai rientra nel tetto della previdenza complementare',
  testRenewalTax: 'Aumenti da rinnovo contrattuale 2026: imposta sostitutiva del 5%',
  testRenewalTreatment: 'Aumenti da rinnovo: contano per la capienza del trattamento integrativo',
  renewalRowLabel: 'Aumenti da rinnovo contrattuale agevolati',
  renewalRowNote: (a1) => `Imposta sostitutiva ${a1}% al posto di IRPEF e addizionali`,
  renewalTaxLabel: 'Imposta sostitutiva sugli aumenti da rinnovo',
  renewalExplanationTitle: 'Aumenti da rinnovo contrattuale',
  renewalExplanationBody: (a1, a2) => `Nel 2026 gli aumenti di stipendio che arrivano da rinnovi dei contratti nazionali firmati dal 2024 al 2026 pagano un’imposta del ${a1}% al posto di IRPEF e addizionali, per chi nel 2025 ha avuto un reddito da lavoro dipendente fino a ${a2}. Valgono le mensilità, tredicesima e quattordicesima comprese; restano fuori una tantum, arretrati per il periodo senza contratto, scatti di anzianità e straordinari. Gli aumenti fanno già parte della RAL: qui si indica solo quanta parte della RAL è aumento. Il calcolo applica la soglia al reddito dell’anno simulato e il ${a1}% all’importo lordo. Chi preferisce la tassazione ordinaria può rinunciare per iscritto.`,
  renewalExplanationSource: 'L. 199/2025, art. 1, c. 7; Agenzia delle Entrate, circolare 2/E del 24/02/2026',
  renewalExplanationAmount: 'Aumenti agevolati',
  testAdditionalRateMonthly: 'Contributo aggiuntivo 1%: prima fascia pensionabile per i soli mesi lavorati',
  testMissingYear: 'Un anno senza regole si ferma con un errore chiaro',
  testSouthernRegions: 'Esoneri per il Sud: le regioni sono quelle della tabella regionale',
  testPartTimeThresholds: 'Part-time: soglie di premio e maggiorazioni sulla retribuzione ridotta',
  testCateringPremiums: 'Pubblici esercizi e turismo: niente imposta del 15% sulle maggiorazioni',
  testRegionalExemptionTotalIncome: 'Valle d’Aosta: esenzione regionale sul reddito complessivo',
  testSurchargesNeedIrpef: 'Addizionali dovute solo se è dovuta l’IRPEF netta',
  withinLimits_1: (a1, a2) => `${a1}: il calcolo usa ${a2}.`,
  YEARS_notes_1: 'Seconda aliquota ridotta al 33% dalla Legge di Bilancio 2026.',
  CONTRACT_TYPES_name_2: 'Tirocinio / stage',
  CONTRACT_TYPES_name_3: 'Apprendistato',
  CONTRACT_TYPES_name_4: 'Tempo determinato',
  CONTRACT_TYPES_name_5: 'Tempo indeterminato',
  CONTRIBUTION_SECTORS_name_18: 'Qualunque organico',
  CONTRIBUTION_SECTORS_name_19: 'Qualunque organico',
  CONTRIBUTION_SECTORS_name_20: 'Agricoltura',
  CONTRIBUTION_SECTORS_name_21: 'Qualunque organico',
  CONTRIBUTION_SECTORS_name_22: 'Artigianato',
  CONTRIBUTION_SECTORS_name_23: 'Industria edile',
  domesticExempt_region_1: 'Campania',
  employeeExplanations_html_27: 'Quota esonerata',
  employeeExplanations_html_28: 'Interamente imponibile',
  employeeExplanations_html_29: 'Compensi agevolati',
  employeeExplanations_html_30: 'Addizionale regionale',
  employeeExplanations_html_31: 'Trattamento integrativo',
  employeeExplanations_html_32: 'IRPEF lorda',
  employeeExplanations_html_33: 'Bonus spettante',
  employeeExplanations_html_34: 'Addizionale comunale',
  employeeExplanations_html_35: 'Quota persa',
  employeeExplanations_html_36: 'IRPEF lorda disponibile',
  employeeExplanations_html_37: 'Imponibile tassato',
  employeeExplanations_html_38: '− quota esclusa',
  employeeExplanations_html_39: 'Spettante',
  employeeExplanations_html_40: 'IRPEF lorda',
  employeeExplanations_html_41: '− prima fascia',
  employeeExplanations_html_42: 'Base contributiva',
  employeeExplanations_html_43: 'Retribuzione maturata',
  employeeExplanations_html_44: '× part-time',
  employeeExplanations_html_45: 'RAL contrattuale',
  employeeExplanations_source_9: 'L. 208/2015, art. 1 c. 182-189; L. 199/2025, art. 1 c. 9',
  employeeExplanations_source_10: 'D.Lgs. 252/2005, art. 8',
  employeeExplanations_source_11: 'L. 213/2023 — resa strutturale dalla L. 207/2024',
  employeeExplanations_source_12: 'TUIR art. 51, comma 3',
  employeeExplanations_source_13: 'TUIR art. 13',
  employeeExplanations_source_14: 'TUIR art. 11 — L. 207/2024',
  employeeExplanations_source_15: 'Art. 3-ter D.L. 384/1992, conv. L. 438/1992',
  employeeExplanations_source_16: (a1) => `Circolari INPS — valori ${a1}`,
  employeeExplanations_title_12: 'Previdenza complementare',
  employeeExplanations_title_13: (a1) => `Addizionale regionale — ${a1}`,
  employeeExplanations_title_14: 'Trattamento integrativo',
  employeeExplanations_title_15: (a1) => `Addizionale comunale — ${a1}`,
  employeeExplanations_title_16: (a1) => `IRPEF lorda ${a1}`,
  employeeExplanations_title_17: 'Retribuzione effettivamente maturata',
  executiveExempt_region_1: 'Campania',
  exemptionStatus_reason_8: 'misura sconosciuta',
  fillSelects_1: (a1) => `Cerca fra ${a1} comuni…`,
  flatRome_region_1: 'Lazio',
  foregoneBlock_6: (a1) => `Pacchetto analizzato: <strong class="text-slate-700">&laquo;${a1}&raquo;</strong>`,
  HIRING_EXEMPTIONS_name_4: 'Bonus ZES Unica Mezzogiorno',
  HIRING_EXEMPTIONS_name_5: 'Bonus Giovani under 35',
  HIRING_EXEMPTIONS_name_6: 'Bonus Donne',
  HIRING_EXEMPTIONS_name_7: 'Decontribuzione Sud — PMI',
  HIRING_EXEMPTIONS_source_2: 'L. 213/2023, art. 1, comma 180 — resa strutturale dalla L. 207/2024',
  HIRING_EXEMPTIONS_source_3: 'L. 199/2025, art. 1, commi 210-213 — INPS circolare n. 82/2026',
  HIRING_EXEMPTIONS_source_4: 'D.L. 60/2024, art. 24 — proroga limitata dal D.L. 200/2025',
  HIRING_EXEMPTIONS_source_5: 'D.L. 62/2026, art. 4, conv. L. 112/2026 — INPS circolare n. 72/2026',
  HIRING_EXEMPTIONS_source_6: 'D.L. 60/2024, art. 22 — proroga limitata dal D.L. 200/2025',
  HIRING_EXEMPTIONS_source_7: 'L. 207/2024, art. 1, commi 406-412 — INPS circolare n. 32/2025',
  industryBracket_fundName_1: 'Previndai',
  items_label_7: 'IRPEF netta',
  openExplanation_1: (a1, a2, a3, a4) => `
    <p class="exp-title">${a1}</p>
    <div class="exp-body">${a2}</div>
    ${a3}
    ${a4}
    <button type="button" class="exp-close">Chiudi</button>`,
  ordRome_region_1: 'Lazio',
  paintOptimisation_6: 'Differenza di costo',
  regionalCases_16: 'tabella 2026: 1,33 / 2,13 / 3,23%',
  regionalCases_17: 'Puglia',
  regionalCases_18: 'tabella 2025: 1,33 / 1,43 / 1,63%',
  regionalCases_19: 'Puglia',
  regionalCases_20: 'Bolzano',
  regionalCases_21: 'Bolzano',
  regionalCases_22: 'Bolzano',
  regionalCases_23: "Valle d'Aosta",
  regionalCases_24: "Valle d'Aosta",
  regionalCases_25: 'Trento',
  regionalCases_26: 'Trento',
  regionalCases_27: 'Friuli-Venezia Giulia',
  regionalCases_28: 'Friuli-Venezia Giulia',
  regionalCases_29: 'Umbria',
  regionalCases_30: 'Umbria',
  regionalCases_31: 'Lazio',
  regionalCases_32: 'Lazio',
  regionalCases_33: 'Lazio',
  regionalCases_34: 'Lazio',
  renderComparison_18: 'Pressione',
  renderComparison_19: 'Pressione fiscale',
  renderComparison_20: (a1, a2, a3, a4, a5, a6, a7, a8, a9) => `<tr class="bg-slate-50"><td class="px-6 py-2 text-xs text-slate-600 align-top">Parametri</td><td class="px-4 py-2 text-right text-xs text-slate-600 align-top">${a1}</td><td class="px-4 py-2 text-right text-xs text-slate-600 align-top">${a2}</td><td class="px-6 py-2"></td></tr>${a3}${a4}${a5}${a6}${a7}${a8}${a9}`,
  renderEmployee_69: 'Buoni pasto esenti',
  renderEmployee_70: 'Fringe benefit esenti',
  renderEmployee_71: 'Trattamento integrativo',
  renderEmployee_72: 'Bonus cuneo fiscale',
  renderEmployee_73: 'Delibera comunale &mdash; anagrafe MEF',
  renderEmployee_74: (a1) => `Addizionale comunale ${a1}`,
  renderEmployee_75: (a1) => `Addizionale regionale ${a1}`,
  renderEmployee_76: 'IRPEF netta',
  renderEmployee_77: 'Art. 12 TUIR',
  renderEmployee_78: 'Art. 12 TUIR',
  renderEmployee_79: 'Art. 12 TUIR',
  renderEmployee_80: 'Art. 13 TUIR',
  renderEmployee_81: 'IRPEF lorda',
  renderEmployee_82: 'Base imponibile effettiva',
  renderEmployee_83: 'Imponibile IRPEF',
  renderEmployee_84: 'Previdenza complementare dedotta',
  renderEmployee_85: (a1) => `Abbattimento &mdash; ${a1}`,
  renderEmployee_86: 'Buoni pasto &mdash; quota eccedente',
  renderEmployee_87: 'Fringe benefit imponibili',
  renderEmployee_88: 'Maggiorazioni notturno, festivo, turni agevolate',
  renderEmployee_89: 'Tassazione ordinaria IRPEF',
  renderEmployee_90: 'Retribuzione maturata',
  renderEmployee_91: (a1) => `part-time ${a1}%`,
  renderEmployee_92: 'RAL contrattuale',
  renderEmployee_93: (a1) => ` · part-time ${a1}%`,
  renderEmployee_html_12: 'Quota TFR',
  renderEmployee_html_13: 'INAIL (ipotesi 0,50%)',
  renderEmployee_html_14: 'Valore percepito',
  renderEmployee_title_3: 'Pressione fiscale',
  ROLES_dirigente_1: 'Dirigente',
  ROLES_impiegato_1: 'Impiegato, quadro, intermedio',
  ROLES_operaio_1: 'Operaio',
  runTests_123: 'Input negativo gestito senza NaN',
  runTests_124: 'Input 0 gestito senza NaN',
  runTests_125: (a1, a2, a3) => `IRPEF ${a1} · regionale ${a2} · comunale ${a3}`,
  runTests_126: (a1, a2) => `${a1} (atteso ${a2})`,
  runTests_127: (a1, a2, a3, a4) => `Addizionale regionale ${a1} ${a2}, ${a3}: ${a4}`,
  runTests_128: 'Dataset: Lombardia 1,23% / 1,58% / 1,72% / 1,73%',
  runTests_129: (a1, a2) => `${a1} comuni · ${a2} regioni`,
  runTests_130: (a1, a2) => `forfetario ${a1} → ${a2}`,
  runTests_131: (a1, a2) => `artigiani ${a1} · commercianti ${a2}`,
  runTests_132: (a1, a2) => `${a1} soluzioni, scelta ${a2}`,
  runTests_133: (a1) => `${a1} province mappate`,
  runTests_134: (a1, a2) => `${a1} combinazioni, ${a2} anomalie`,
  runTests_135: (a1, a2) => `dirigente ${a1} · domestico ${a2}`,
  runTests_136: (a1, a2, a3) => `${a1}: datore ${a2} contro ${a3}`,
  runTests_137: (a1, a2) => `${a1}: ${a2} recuperati`,
  runTests_138: 'Ottimizzazione dal budget: stessa spesa, valore crescente',
  runTests_139: (a1, a2) => `richiesti ${a1}, applicati ${a2}`,
  runTests_140: (a1, a2) => `${a1} combinazioni, ${a2} anomalie`,
  runTests_141: (a1, a2) => `richiesti ${a1}, trattenuti ${a2}`,
  runTests_142: 'IRPEF netta mai negativa (1k → 200k)',
  runTests_143: 'RAL 30.000 — imponibile = 27.243,00 €',
  SELF_EMPLOYED_REGIMES_name_2: 'Forfetario 5%',
  SELF_EMPLOYED_REGIMES_name_3: 'Forfetario 15%',
  selfEmployedExplanations_4: '− costi deducibili',
  selfEmployedExplanations_html_21: 'Prelievo',
  selfEmployedExplanations_html_22: 'IRPEF netta',
  selfEmployedExplanations_html_23: 'IRPEF lorda',
  selfEmployedExplanations_html_24: 'IRPEF lorda',
  selfEmployedExplanations_html_25: 'Imponibile',
  selfEmployedExplanations_html_26: 'Imponibile',
  selfEmployedExplanations_html_27: 'Imponibile',
  selfEmployedExplanations_html_28: 'Base contributiva',
  selfEmployedExplanations_html_29: '− costi deducibili',
  selfEmployedExplanations_html_30: '× coefficiente ATECO',
  selfEmployedExplanations_title_9: 'IRPEF lorda',
  selfEmployedExplanations_title_10: 'Imponibile fiscale',
  southInside_region_1: 'Campania',
  TAX_REGIMES_name_3: 'Frontalieri — franchigia 10.000 €',
  TAX_REGIMES_name_4: 'Impatriati — D.Lgs. 209/2023',
  thresholds_name_7: 'Trattamento integrativo',
  top_9: 'Copia CSV',
  top_10: 'Copia CSV',
  top_11: 'Copiato',
  updateContextNotes_18: 'RAL contrattuale',
  updateSelfEmployed_32: 'Addizionale comunale',
  updateSelfEmployed_33: 'Addizionale regionale',
  updateSelfEmployed_34: (a1) => `Scaglioni ${a1}`,
  updateSelfEmployed_35: 'IRPEF lorda',
  updateSelfEmployed_36: 'Imponibile fiscale',
  updateSelfEmployed_37: 'Costi deducibili',
  YEARS_notes_2: 'Aliquote IRPEF 23% / 35% / 43% (L. 207/2024).'
};
