/* Build the Tailwind stylesheet and embed it in index.html.
 *
 *   node tools/build_css.js           rewrite the block in the page
 *   node tools/build_css.js --check   do not write, only say if it is stale
 *
 * Why not the CDN: cdn.tailwindcss.com compiles the CSS in the visitor's
 * browser. That costs a request to a third party (which sees the visitor's IP
 * address), a console warning that the CDN is not for production, and a
 * moment of unstyled page. Here the stylesheet is built once and travels
 * inside the page.
 *
 * The price is that the CSS is generated content: a class added to the markup
 * or to a template in src/ has no rules until the block is rebuilt. That is
 * why --check exists, and CI runs it on every push.
 *
 * Exit code 0 when the block is up to date, 10 when it was rewritten (or,
 * with --check, when it should be).
 */
const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const INDEX = path.join(ROOT, 'index.html');
const BEGIN = '/* === BEGIN TAILWIND CSS: generated by tools/build_css.js === */';
const END = '/* === END TAILWIND CSS === */';
const TAILWIND = 'tailwindcss@3.4.19';

// Classes live in the page and in the HTML templates of the UI and texts modules.
const SOURCES = ['src/ui', 'src/texts'];

/* Tailwind reads a copy of index.html without the generated block: class
 * names also appear in the CSS selectors, and scanning its own output would
 * make the stylesheet grow at every run. */
const configFor = (files) => `module.exports = {
  content: ${JSON.stringify(files)},
  theme: { extend: { colors: { brand: {
    50: '#eef4ff', 100: '#dae6ff', 200: '#bcd2ff', 300: '#8fb4ff',
    400: '#5b8cfd', 500: '#3665f5', 600: '#2148e3', 700: '#1b39c0',
    800: '#1c339c', 900: '#1d307b'
  } } } },
  plugins: []
};
`;

function buildCss(markup) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tw-'));
  const page = path.join(tmp, 'page.html');
  fs.writeFileSync(page, markup);
  const files = [page.replace(/\\/g, '/')];
  for (const dir of SOURCES) {
    for (const f of fs.readdirSync(path.join(ROOT, dir))) {
      if (f.endsWith('.js')) files.push(path.join(ROOT, dir, f).replace(/\\/g, '/'));
    }
  }
  const config = path.join(tmp, 'tailwind.config.js');
  const input = path.join(tmp, 'in.css');
  const output = path.join(tmp, 'out.css');
  fs.writeFileSync(config, configFor(files));
  fs.writeFileSync(input, '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n');
  execFileSync('npx', ['--yes', TAILWIND, '-c', config, '-i', input, '-o', output, '--minify'],
               { stdio: ['ignore', 'ignore', 'inherit'], shell: process.platform === 'win32' });
  const css = fs.readFileSync(output, 'utf8').trim();
  fs.rmSync(tmp, { recursive: true, force: true });
  return css;
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const pageText = fs.readFileSync(INDEX, 'utf8');
  const a = pageText.indexOf(BEGIN);
  const b = pageText.indexOf(END);
  if (a === -1 || b === -1) {
    console.error('CSS block markers not found in index.html.');
    return 1;
  }
  const current = pageText.slice(a + BEGIN.length, b).trim();
  const withoutBlock = pageText.slice(0, a + BEGIN.length) + pageText.slice(b);
  const fresh = buildCss(withoutBlock);

  if (current === fresh) {
    console.log('CSS already matches the markup: no class added or removed.');
    return 0;
  }
  if (checkOnly) {
    console.error('The CSS in the page does not match the markup: run node tools/build_css.js');
    return 10;
  }
  const eol = pageText.includes('\r\n') ? '\r\n' : '\n';
  fs.writeFileSync(INDEX, pageText.slice(0, a + BEGIN.length) + eol + fresh + eol + pageText.slice(b));
  console.log(`CSS rebuilt: ${Math.round(fresh.length / 1024)} KB embedded in index.html.`);
  return 10;
}

process.exit(main());
